Properly acknowledge received data
This call is required for hyper-h2 to properly manage the HTTP2 flow
control window; without this connections will eventually die with:

    h2.exceptions.FlowControlError: Flow control window shrunk below 0

This fixes the issue.